def validated = AWSResources(params)

pipeline {
  agent any

    parameters {
        choice(name: 'ACTION',
               choices: ['plan','apply','destroy'],
               description: 'terraform action to perform')
        string(name: 'ZONE', defaultValue: '', description: 'AWS availability zone')
        choice(name: 'REGION',
               choices: ['N. Virginia','Ohio','...'],
               description: 'AWS region')
        choice(name: 'RESOURCE',
               choices: ['vpc','instance','container','s3'],
               description: 'resource type')
        string(name: 'NAME', defaultValue: '', description: 'resource name')
    }
}